# Generated by Django 4.1 on 2022-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnglishWordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_word", models.CharField(max_length=35)),
                ("japanese_word", models.CharField(max_length=35)),
                ("check_count", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
